name: max31865
description: Driver for MAX31865 RTD-to-Digital Converter.
dependencies:
  resistance_to_temperature:
    url: github.com/toitware/toit-resistance-to-temperature
    version: ^1.0.0

environment:
  sdk: ^2.0.0-alpha.180
